[package]
name = "tppl"
edition = "2021"
version = "0.1.0"
authors = ["Dietrich Geisler <email>", "Peter Chon <email>"]
description = ""
documentation = ""
homepage = ""
repository = "https://github.com/Checkmate50/tppl"
readme = "README.md"
keywords = []
categories = []
license = "MIT"


[dependencies]
chumsky = "0.8.0"
petgraph = "0.4.13"
rand = "0.8.5"
rand_distr = "0.4.3"
plotters = "0.3.2"
clap = { version = "3.2.17", features = ["derive"]}